//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigIntegerProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class testTable_1
    {
        public long Id { get; set; }
        public Nullable<long> NameId { get; set; }
        public string QRString { get; set; }
    }
}
