//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int MemberID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string HouseID { get; set; }
        public string CadetNo { get; set; }
        public Nullable<int> BatchID { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string CountryID { get; set; }
        public Nullable<int> ChapterID { get; set; }
        public string HomePhone { get; set; }
        public string CellPhone { get; set; }
        public string Fax { get; set; }
        public string HomeEmail { get; set; }
        public string HomeFax { get; set; }
        public string Picture { get; set; }
        public string Password { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> ProfessionID { get; set; }
        public string Major { get; set; }
        public string Specialty { get; set; }
        public string Blurb { get; set; }
        public bool Voter { get; set; }
        public bool BatchRep { get; set; }
        public bool Expired { get; set; }
        public bool LifeTimeMember { get; set; }
        public bool SubscriptionPaid { get; set; }
        public string SubscriptionDueDate { get; set; }
        public string DateOfBirth { get; set; }
        public string BloodGroup { get; set; }
        public string MarriageDate { get; set; }
        public string WorkAddress { get; set; }
        public string WorkCity { get; set; }
        public string WorkState { get; set; }
        public string WorkCountryID { get; set; }
        public string WorkPhone { get; set; }
        public string WorkFax { get; set; }
        public string WorkEmail { get; set; }
        public string ParmanentAddress { get; set; }
        public string ParmanentCity { get; set; }
        public string ParmanentZip { get; set; }
        public string ParmanentState { get; set; }
        public string ParmanentCountryID { get; set; }
        public string ParmanentPhone { get; set; }
        public string ParmanentEmail { get; set; }
        public string Employer { get; set; }
        public string SpouseFirstName { get; set; }
        public string SpouseLastName { get; set; }
        public string SpouseDateOfBirth { get; set; }
        public string SpouseBloodGroup { get; set; }
        public string SpouseMajor { get; set; }
        public Nullable<int> SpouseProfessionID { get; set; }
        public string SpouseSpecialty { get; set; }
        public Nullable<int> DegreeID { get; set; }
        public string ShortBiography { get; set; }
        public string ElectionPasscode { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
