//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BestowersAppDatabase_OldEntities : DbContext
    {
        public BestowersAppDatabase_OldEntities()
            : base("name=BestowersAppDatabase_OldEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Member> Members { get; set; }
    
        public virtual ObjectResult<Member_Proc_Result> Member_Proc(Nullable<int> memberID, string firstName, string lastName, Nullable<int> batchID, Nullable<int> cadetNo, string homeEmail, string homePhone, string city, string state, string countryID)
        {
            var memberIDParameter = memberID.HasValue ?
                new ObjectParameter("MemberID", memberID) :
                new ObjectParameter("MemberID", typeof(int));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var batchIDParameter = batchID.HasValue ?
                new ObjectParameter("BatchID", batchID) :
                new ObjectParameter("BatchID", typeof(int));
    
            var cadetNoParameter = cadetNo.HasValue ?
                new ObjectParameter("CadetNo", cadetNo) :
                new ObjectParameter("CadetNo", typeof(int));
    
            var homeEmailParameter = homeEmail != null ?
                new ObjectParameter("HomeEmail", homeEmail) :
                new ObjectParameter("HomeEmail", typeof(string));
    
            var homePhoneParameter = homePhone != null ?
                new ObjectParameter("HomePhone", homePhone) :
                new ObjectParameter("HomePhone", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            var countryIDParameter = countryID != null ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Member_Proc_Result>("Member_Proc", memberIDParameter, firstNameParameter, lastNameParameter, batchIDParameter, cadetNoParameter, homeEmailParameter, homePhoneParameter, cityParameter, stateParameter, countryIDParameter);
        }
    
        public virtual ObjectResult<sortData_Result> sortData(string data)
        {
            var dataParameter = data != null ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sortData_Result>("sortData", dataParameter);
        }
    }
}
