//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalCalculation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GetFromRentMan
    {
        public int Id { get; set; }
        [Required]
        public Nullable<decimal> ReceiveMoney { get; set; }
        public Nullable<decimal> DueMoney { get; set; }
        public Nullable<decimal> Rent { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ProjectId { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
