//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalCalculation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Expences = new HashSet<Expence>();
            this.GetFromRentMen = new HashSet<GetFromRentMan>();
            this.ProjectMembers = new HashSet<ProjectMember>();
            this.TotalMoneyCalculationForRentMen = new HashSet<TotalMoneyCalculationForRentMan>();
        }
    
        public int Id { get; set; }
        [Required]
        public string ProjectName { get; set; }
        public string Description { get; set; }
        [Required]
        public Nullable<decimal> Invest { get; set; }
        [Required]
        public Nullable<decimal> Rent { get; set; }
        public Nullable<int> PartnerNumber { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Date { get; set; }
        public string CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expence> Expences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GetFromRentMan> GetFromRentMen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectMember> ProjectMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TotalMoneyCalculationForRentMan> TotalMoneyCalculationForRentMen { get; set; }
    }
}
