//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalCalculation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalMoneyCalculationForRentMan
    {
        public int Id { get; set; }
        public Nullable<decimal> TotalPayable { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
        public Nullable<decimal> TotalDue { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public Nullable<int> ProjectId { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
