//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIU_CPC_BlueDivision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProblemsStudent
    {
        public string Comment { get; set; }
        public string IsSolved { get; set; }
        public int ProblemId { get; set; }
        public string StudentId { get; set; }
    
        public virtual Problem Problem { get; set; }
        public virtual Student Student { get; set; }
    }
}
