//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIU_CPC_BlueDivision.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Problem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Problem()
        {
            this.ProblemsStudents = new HashSet<ProblemsStudent>();
        }
    
        public int Id { get; set; }
        [Required]
        public string ProblemName { get; set; }
        [Required]
        public string ProblemLink { get; set; }
        public string Comment { get; set; }
        public Nullable<int> BlueSheetId { get; set; }
        public Nullable<int> ProblemSolverCount { get; set; }
    
        public virtual BlueSheet BlueSheet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProblemsStudent> ProblemsStudents { get; set; }
    }
}
