//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIU_CPC_BlueDivision.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.ProblemsStudents = new HashSet<ProblemsStudent>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string StudentId { get; set; }
        public string FullName { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string Semester { get; set; }
        public Nullable<int> SolveCount { get; set; }
        public string CodeForcesId { get; set; }
        public string MuteOrUnmute { get; set; }
        public Nullable<int> Request { get; set; }
        public byte[] StudentImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProblemsStudent> ProblemsStudents { get; set; }
    }
}
