//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRCodeGenerator_AudioVideoImage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class QRCodeString_tbl
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public byte[] QRCodeImage { get; set; }
        [Required]
        public string QRCodeString { get; set; }
    }
}
