//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technical_Assessment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPostComment
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public Nullable<int> Like { get; set; }
        public Nullable<int> Dislike { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> BlogPostId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual BlogPost BlogPost { get; set; }
        public virtual User User { get; set; }
    }
}
