//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudOperation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int Id { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Provide First Name")]
        public string FirstName { get; set; }
        [Required (AllowEmptyStrings = false, ErrorMessage = "Please Provide Last Name")]
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
    }
}
