// <auto-generated />
namespace Sina.Trainings.AECustomIdentity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FullNameAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FullNameAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201703200630547_FullNameAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
