//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajax_based_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTable
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> TotalMark { get; set; }
    }
}
