//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InputFromExcelFile.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConConEntities : DbContext
    {
        public ConConEntities()
            : base("name=ConConEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContestantsTable> ContestantsTables { get; set; }
        public virtual DbSet<ContestContestant> ContestContestants { get; set; }
        public virtual DbSet<ContestTable> ContestTables { get; set; }
    }
}
