//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InputFromExcelFile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContestantsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContestantsTable()
        {
            this.ContestContestants = new HashSet<ContestContestant>();
        }
    
        public int Id { get; set; }
        public string ContestantsName { get; set; }
        public string StudentId { get; set; }
        public string CFHandle { get; set; }
        public string CFHandleLink { get; set; }
        public Nullable<decimal> Score { get; set; }
        public Nullable<int> TotalSolve { get; set; }
        public Nullable<int> TotalParticipation { get; set; }
        public Nullable<int> OnlineParticipation { get; set; }
        public Nullable<int> SolveCountOnsite { get; set; }
        public Nullable<int> SolveCountUpsolves { get; set; }
        public Nullable<decimal> AverageSolvePerContest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContestContestant> ContestContestants { get; set; }
    }
}
