//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InputFromExcelFile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContestContestant
    {
        public int Id { get; set; }
        public Nullable<int> ContestId { get; set; }
        public Nullable<int> ContestantId { get; set; }
        public string ContestTimeSolve { get; set; }
        public string UpSolve { get; set; }
    
        public virtual ContestantsTable ContestantsTable { get; set; }
        public virtual ContestTable ContestTable { get; set; }
    }
}
