//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software_Company_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Blog_tbl
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        //[Required] required dile hoy na keno..?
        public byte[] BlogImage { get; set; }
        [Required]
        public string Text { get; set; }
        public string BlogDivId { get; set; }
    }
}
