//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software_Company_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInformation
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string UserName { get; set; }
        public string Address { get; set; }
        public byte[] EmployeeImage { get; set; }
        public string DateOfBirth { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string BloodGroup { get; set; }
        public string Religion { get; set; }
        public string Nationality { get; set; }
        public string AboutYou { get; set; }
        public string AlternativeEmail { get; set; }
        public string PostOffice { get; set; }
        public string District { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public string PassportNo { get; set; }
        public string Designation { get; set; }
        public string JobExperience { get; set; }
    }
}
