//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software_Company_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FoundationDayTShirtDistribution
    {
        public int ID { get; set; }
        public string StudentID { get; set; }
        public string TokenNumber { get; set; }
        public string TShirtSize { get; set; }
        [Required]
        public string QRCode { get; set; }
    }
}
