//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software_Company_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Gallery_tbl
    {
        public int Id { get; set; }
        // bal [Required] dile kaj kore na.. onno way te required er kaj solve kore disi. :)
        // GalleryPostController.cs file er create action ta dekho.
        public byte[] GalleryImage { get; set; }
    }
}
