//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software_Company_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OurTeam
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string WorkingSince { get; set; }
        public byte[] EmployeeImage { get; set; }
    }
}
