//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Googlemaps
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolInfo
    {
        public string SchoolId { get; set; }
        public string SchoolName { get; set; }
        public System.Data.Spatial.DbGeography GeoLocation { get; set; }

    }
}
