//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software_Company_Website.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContactUs_DBEntities : DbContext
    {
        public ContactUs_DBEntities()
            : base("name=ContactUs_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PersonMessage_tbl> PersonMessage_tbl { get; set; }

        public System.Data.Entity.DbSet<Software_Company_Website.Models.JobCVPdf_tbl> JobCVPdf_tbl { get; set; }
    }
}
