//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullCRUDImplementationWithJquery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartment
    {
        public tblDepartment()
        {
            this.tblStudents = new HashSet<tblStudent>();
        }
    
        public int DepartmentId { get; set; }
        public string DepartmentName { get; set; }
    
        public virtual ICollection<tblStudent> tblStudents { get; set; }
    }
}
